export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_IS_AUTHED = 'SET_IS_AUTHED';
export const USER_LOGIN_USER_SUCCESS = 'USER_LOGIN_USER_SUCCESS';
export const GENERE_SUCCESS = 'GENERE_SUCCESS';



